In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('../classification_results_trial_0001.csv')
data.head()

      image_path real_class predicted_class  prob_benign  prob_malign
0  image_001.jpg     malign          malign     0.031429     0.968571
1  image_002.jpg     benign          benign     0.636410     0.363590
2  image_003.jpg     malign          malign     0.314356     0.685644
3  image_004.jpg     benign          benign     0.508571     0.491429
4  image_005.jpg     benign          benign     0.907566     0.092434

1. Quantas imagens são “benign” e “malign” em real_class?

In [5]:
data['real_class'].value_counts()

real_class
malign    55
benign    45
Name: count, dtype: int64

2. Identifique em quais imagens o modelo errou a predição.

In [11]:
erros = data[data['real_class']!=data['predicted_class']]
erros['image_path']

20    image_021.jpg
26    image_027.jpg
27    image_028.jpg
41    image_042.jpg
46    image_047.jpg
65    image_066.jpg
67    image_068.jpg
69    image_070.jpg
70    image_071.jpg
76    image_077.jpg
80    image_081.jpg
91    image_092.jpg
Name: image_path, dtype: object

3. Verifique se o modelo estava confiante mesmo quando errou.

In [13]:
# Ver a probabilidade da classe predita (confiança)
erros['confianca'] = erros.apply(
    lambda row: row['prob_malign'] if row['predicted_class'] == 'maligna' else row['prob_benign'],
    axis=1
)

erros['confianca'].describe()

C:\Users\Hanny\AppData\Local\Temp\ipykernel_18600\2244965945.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  erros['confianca'] = erros.apply(

count    12.000000
mean      0.630586
std       0.245829
min       0.186519
25%       0.528436
50%       0.684251
75%       0.822337
max       0.897216
Name: confianca, dtype: float64

In [14]:
erros['confianca']

20    0.807440
26    0.818015
27    0.860731
41    0.251782
46    0.609564
65    0.835302
67    0.186519
69    0.590893
70    0.677564
76    0.690938
80    0.341066
91    0.897216
Name: confianca, dtype: float64

4. Calcule: <br>
a. TP (real malign, previsto malign) <br>
b. TN (real benign, previsto benign) <br>
c. FP (real benign, previsto malign) <br>
d. FN (real malign, previsto benign) <br>

In [15]:
TP = len(data[(data['real_class'] == 'malign') & (data['predicted_class'] == 'malign')])
TN = len(data[(data['real_class'] == 'benign') & (data['predicted_class'] == 'benign')])
FP = len(data[(data['real_class'] == 'benign') & (data['predicted_class'] == 'malign')])
FN = len(data[(data['real_class'] == 'malign') & (data['predicted_class'] == 'benign')])

In [16]:
print(f'TP: {TP}, TN: {TN}, FP: {FP}, FN: {FN}')

TP: 46, TN: 42, FP: 3, FN: 9

5. Calcule: <br>
a. Acurácia: (TP+TN)/(TP+TN+FP+FN) <br>
b. Precisão: TP/(TP+FP) <br>
c. Recall: TP/(TP+FN) <br>
d. Especificidade: TN/(TN+FP) <br>

In [17]:
accuracy = (TP + TN) / (TP + TN + FP + FN)
precision = TP / (TP + FP)
recall = TP / (TP + FN)
specificity = TN / (TN + FP)

print(f'Accuracy: {accuracy:.2f}')
print(f'Precision: {precision:.2f}')
print(f'Recall: {recall:.2f}')
print(f'Specificity: {specificity:.2f}')

Accuracy: 0.88
Precision: 0.94
Recall: 0.84
Specificity: 0.93

6. Encontre as 5 imagens benign com menor prob_benign. O que isso pode 
indicar? 

Considerando o acerto dos dados quanto à classe verdadeira, provavelmente indica que os padrões observados na imagem eram muito pouco semelhantes aos padrões esperados pela classe benigna

In [18]:
data.sort_values(by="prob_benign", ascending=True).head(5)

       image_path real_class predicted_class  prob_benign  prob_malign
28  image_029.jpg     malign          malign     0.006952     0.993048
71  image_072.jpg     malign          malign     0.016588     0.983412
0   image_001.jpg     malign          malign     0.031429     0.968571
45  image_046.jpg     malign          malign     0.036887     0.963113
68  image_069.jpg     malign          malign     0.040775     0.959225

7. Encontre as 5 imagens malign com maior prob_benign. O que isso pode 
indicar?

Considerando o acerto dos dados quanto à classe verdadeira, provavelmente indica que os padrões observados na imagem eram muito pouco semelhantes aos padrões esperados pela classe maligna

In [19]:
data.sort_values(by="prob_malign", ascending=True).head(5)

       image_path real_class predicted_class  prob_benign  prob_malign
54  image_055.jpg     benign          benign     0.985650     0.014350
39  image_040.jpg     benign          benign     0.971782     0.028218
40  image_041.jpg     benign          benign     0.962447     0.037553
34  image_035.jpg     benign          benign     0.942910     0.057090
78  image_079.jpg     benign          benign     0.936730     0.063270